apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: dev-nginx-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /ci
        backend:
          serviceName: helmed-jenkins
          servicePort: 8080

